name: Deploy Frontend to Firebase

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'   # Só dispara quando editares ficheiros do frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
